config/routes.rb
Rabotnik::Application.routes.draw do

  resources :projects do
    resource :keyword_import, :only => [:new, :create]
    resources :keywords do
      put 'cluster', :on => :collection
    end
  end

  mount BeanstalkdView::Server, :at => "/beanstalkd"

end

app/models/cluster_project.rb
class ClusterProject

  attr_reader :project

  def initialize(project)
    @project = project
  end
  
  def cluster
    keywords = @project.keywords.all
    Parallel.each(keywords) do |keyword|
      ActiveRecord::Base.connection.reconnect!
      keyword.cluster!
      @project.update_progress
    end
    ActiveRecord::Base.verify_active_connections!
  end
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :project
  attr_accessible :content, :munged_content

  after_save :update_project

  paginates_per 10

  def update_project
    self.project.invalidate_clustering
  end

  def cluster!
    self.munged_content = BCrypt::Password.create(content, :cost => cost_factor)
    save!
  end

  private

  def cost_factor
    13
  end
end

app/models/keyword_import.rb
class KeywordImport
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def initialize(attributes = {})
    @keywords = attributes[:keywords]
    if attributes[:project]
      @project = attributes[:project]
    end
    if attributes[:project_id]
      @project = Project.find attributes[:project_id]
    end
  end

  def persisted?
    false
  end

  def keywords
    @keywords
  end

  def import
    @keywords.split("\n").compact.each do |keyword|
      @project.keywords.create(content: keyword)
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :progress, :as => :system
  has_many :keywords

  state_machine :initial => :clustered do

    before_transition :needs_clustering => :being_clustered, :do => :reset_progress
    #before_transition :started => :finished, :do => :before_finish
    #before_transition :started => :failed, :do => :before_stall

    event :cluster do
      transition :needs_clustering => :being_clustered
    end

    event :finish_clustering do
      transition :being_clustered => :clustered
    end


    event :invalidate_clustering do
      transition :clustered => :needs_clustering
    end

    state :needs_clustering do
    end

    state :being_clustered do
    end

    state :clustered do
    end

  end

  def reset_progress
    self.class.connection.execute("UPDATE projects SET progress = 0 WHERE id = #{id}")
  end

  def update_progress
    self.class.update_counters(self.id, :progress => 1)
  end

  def percent_done
    (progress / keywords.count.to_f ) * 100
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/keyword_imports_controller.rb
class KeywordImportsController < ApplicationController

  before_filter :set_project

  def set_project
    @project = Project.find(params[:project_id]) 
  end

  def new
    @keyword_import = KeywordImport.new(:project => @project)
  end
  
  def create
    @keyword_import = KeywordImport.new(params[:keyword_import].merge(project: @project))
    if @keyword_import.import
      redirect_to project_keywords_url(@project, @keywords), :notice => "Keywords imported"
    else
      render action: new
    end
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  # GET /keywords
  # GET /keywords.json
  before_filter :set_project

  def set_project
    if params['project_id']
      @project = Project.find(params['project_id'])
    end
  end
  def index
    @keywords = @project.keywords.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @keywords }
    end
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
    @keyword = Keyword.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @keyword }
    end
  end

  # GET /keywords/new
  # GET /keywords/new.json
  def new
    @keyword = @project.keywords.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @keyword }
    end
  end

  # GET /keywords/1/edit
  def edit
    @keyword = @project.keywords.find(params[:id])
  end

  # POST /keywords
  # POST /keywords.json
  def create
    
    @keyword = @project.keywords.build(params[:keyword])

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to [@project, @keyword], notice: 'Keyword was successfully created.' }
        format.json { render json: @keyword, status: :created, location: [@project, @keyword] }
      else
        format.html { render action: "new" }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /keywords/1
  # PUT /keywords/1.json
  def update
    @keyword = @project.keywords.find(params[:id])

    respond_to do |format|
      if @keyword.update_attributes(params[:keyword])
        format.html { redirect_to [@project, @keyword], notice: 'Keyword was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword = @project.keywords.find(params[:id])
    @keyword.destroy

    respond_to do |format|
      format.html { redirect_to project_keywords_url(@project) }
      format.json { head :no_content }
    end
  end

  def cluster
    @project.cluster
    Backburner.enqueue(ClusterJob,@project.id)
    redirect_to project_keywords_url(@project), :notice => "Project is being clustered"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/keyword_imports/_form.html.erb
<%= form_for([@project, @keyword_import], url: project_keyword_import_path) do |f| %>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_area :keywords, :cols => 40, :rows => 40%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keyword_imports/new.html.erb
<h1>New keyword import</h1>

<%= render 'form' %>

app/views/keywords/_form.html.erb
<%= form_for([@project, @keyword]) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :munged_content %><br />
    <%= f.text_field :munged_content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', [@project, @keyword] %> |
<%= link_to 'Back', project_keywords_path(@project) %>

app/views/keywords/index.html.erb
<h1>Listing keywords for <%= @project.name %></h1>

Project state: <%= @project.state %>
<% if @project.being_clustered? %>
  (<%= sprintf("%.2f %%",@project.percent_done) %>)
<% end %>
<br />

<%= paginate @keywords %>
<table>
  <tr>
    <th>Content</th>
    <th>Munged content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @keywords.each do |keyword| %>
  <tr>
    <td><%= keyword.content %></td>
    <td><%= keyword.munged_content %></td>
    <td><%= link_to 'Show', [@project,keyword], :class => "button" %></td>
    <td><%= link_to 'Edit', edit_project_keyword_path(@project,keyword), :class => "button" %></td>
    <td><%= link_to 'Destroy', [@project, keyword], method: :delete, data: { confirm: 'Are you sure?' }, :class => "button" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Import Keywords', new_project_keyword_import_path(@project), :class => "button" %>
<%= link_to 'New Keyword', new_project_keyword_path(@project), :class => "button" %>

<%= form_for(@project, :url => cluster_project_keywords_path(@project), :as => :put) do |f| %>
  <%= f.submit("Cluster", :class => "button", :disabled => !@project.can_cluster?) %>
<% end %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', project_keywords_path(@project) %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @keyword.content %>
</p>

<p>
  <b>Munged content:</b>
  <%= @keyword.munged_content %>
</p>

<p>
  <b>Project:</b>
  <%= @keyword.project.name %>
</p>


<%= link_to 'Edit', edit_project_keyword_path(@project, @keyword) %> |
<%= link_to 'Back', project_keywords_path(@project) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <div class="row">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div data-alert class="alert-box">
          <%= msg %>
          <a href="#" class="close">&times;</a>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>
<p>
  <b>Keywords:</b>
  <%= link_to @project.keywords.count, project_keywords_path(@project) %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>